### ISSUE TITLE
IQueueMessageEventHandler does not trigger events in the right order

### ISSUE THREAD

**Issue by DoubleDBE** [horse-framework/horse-messaging#158]
Not sure if this is an actual bug or not, but still wanted to report it anyway.

It seems like `IQueueMessageEventHandler` isn't getting triggered in the right order.

As you can see in the screenshot, `OnConsumed` is called before `OnProduced`.

I have no special code in this handler, except a `Console.WriteLine` call and a simple `Task.CompletedTask` return.

![image](https://user-images.githubusercontent.com/45478482/213877801-0b8d2665-b570-40b8-a90a-ff6f9c9e330d.png)

**Comment by mhelvacikoylu** [comment]
OnProduced event is triggered after message added into queue. (and after saved persistently if queue is persistent)
Because we want to be sure server saved the message before trigger OnProduced event.

But at same time another process finds next message in queue and sends the message to the consumers. Usually that process can handle the message quickly and sends to consumer before OnProduced trigger operation completed. I said usually because adding into message operation immediately trigger that operation if it's in **delayed mode**. And that causes to this issue. I'm unsure if it should be fixed or not. Because not fixing it gives us immediate consume operation right after a message is produced and it reduces latency from producer to consumer.

Delayed mode mean there are no active consumers in queue. And it makes some operations slower and in longer intervals for using lower resource. When an operation is executed, it starts working fast again. And delayed mode guarantees queue never gets on stuck even some operations can't trigger the sending operation.
